name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build in Android Container
      run: |
        echo "Building App Package..."

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Ratibi-App
        path: .
